services:
  postgres:
    image: postgres:18
    container_name: chessapp-postgres
    environment:
      POSTGRES_DB: chessapp
      POSTGRES_USER: chessapp
      POSTGRES_PASSWORD: chessapp
    ports:
      - "5432:5432"
    volumes:
      - chessapp-postgres-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chessapp -d chessapp"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  chessapp-postgres-data:
